services:
  db:
    image: postgres:17-alpine3.22
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: myapp_dev
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/00_schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser -d myapp_dev"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://devuser:devpass@db:5432/myapp_dev
    working_dir: /app
    volumes:
      - ./:/app:rw
    command: ["gunicorn", "app:server"]
    # command: ["python", "main.py"]
    ports:
      - "8000:8000"

volumes:
  pg_data:
